post:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  lidar_controller:
    type: effort_controllers/JointPositionController
    joint: lidar_rad
    pid: {p: 100.0, i: 0.01, d: 10.0}

  tilt_controller:
    type: effort_controllers/JointPositionController
    joint: xtion_tilt
    pid: {p: 100.0, i: 0.01, d: 10.0}

  pan_controller:
    type: effort_controllers/JointPositionController
    joint: xtion_pan
    pid: {p: 100.0, i: 0.01, d: 10.0}